// <auto-generated />
using System;
using MedicalAttach.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedicalAttach.DataAccess.Migrations
{
    [DbContext(typeof(MedicalAttachDbContext))]
    partial class MedicalAttachDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicalAttach.DataAccess.Entities.AttachmentRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MedicalOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalOrganizationId");

                    b.HasIndex("PatientId");

                    b.ToTable("AttachmentRequests");
                });

            modelBuilder.Entity("MedicalAttach.DataAccess.Entities.MedicalOrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("MedicalOrganizations");
                });

            modelBuilder.Entity("MedicalAttach.DataAccess.Entities.PatientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IIN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IIN")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MedicalAttach.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("MedicalOrganizationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("MedicalOrganizationID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MedicalAttach.DataAccess.Entities.AttachmentRequestEntity", b =>
                {
                    b.HasOne("MedicalAttach.DataAccess.Entities.MedicalOrganizationEntity", "MedicalOrganization")
                        .WithMany("AttachmentRequests")
                        .HasForeignKey("MedicalOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAttach.DataAccess.Entities.PatientEntity", "Patient")
                        .WithMany("AttachmentRequests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalOrganization");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalAttach.DataAccess.Entities.UserEntity", b =>
                {
                    b.HasOne("MedicalAttach.DataAccess.Entities.MedicalOrganizationEntity", "MedicalOrganization")
                        .WithMany("Users")
                        .HasForeignKey("MedicalOrganizationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalOrganization");
                });

            modelBuilder.Entity("MedicalAttach.DataAccess.Entities.MedicalOrganizationEntity", b =>
                {
                    b.Navigation("AttachmentRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MedicalAttach.DataAccess.Entities.PatientEntity", b =>
                {
                    b.Navigation("AttachmentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
